### ISSUE TITLE
Incorrect number sign in Shrink steps

### ISSUE THREAD

**Issue by lesha1201** [telagraphic/flexulator#2]
![image](https://user-images.githubusercontent.com/10157660/54884112-1d8aeb00-4e7e-11e9-89ef-52da31edacb6.png)

Remaining Space = `-1000px`

`[Value] * -Remaing Space = [ 1 * 1000 ] / (3000) = .333 * -1000 = -333.33px`

should be

`[Value] * -Remaing Space = [ 1 * 1000 ] / (3000) = .333 * -(-1000) = 333.33px`

**Comment by telagraphic** [comment]
I'm following this formula - [Understanding Flexbox](https://www.madebymike.com.au/writing/understanding-flexbox/).  Does that make sense?

I'm open to changing the formula as above if people feel it makes more sense.

**Comment by lesha1201** [comment]
@telagraphic Then you should change formula to: `... = [Value] * Remaining Space = Shrink Amount`

**Comment by telagraphic** [comment]
Fixed
