### ISSUE TITLE
Wrong results with float numbers

### ISSUE THREAD

**Issue by everdimension** [telagraphic/flexulator#3]
Example:

![image](https://user-images.githubusercontent.com/5347023/55151857-31756c00-5160-11e9-8f34-b64ae0118b17.png)

Reason:

You're using `parseInt` here: https://github.com/telagraphic/flexulator/blob/d4d4f38002002d5b6e5ed751ca59459af9cb1550/js/main.js#L489

...but `itemGrow` may be a float (e.g. `flew-grow: 0.4`)

`parseFloat` seems like a better fit.

**Comment by telagraphic** [comment]
Thanks, good call!
